CREATE DATABASE IF NOT EXISTS COLLAGE_ATTINMENT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE college_attainment;

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(80) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  display_name VARCHAR(120) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS program_exit_survey (
  sr INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, acad_year VARCHAR(20) NOT NULL,
  po1 DOUBLE NOT NULL DEFAULT 0, po2 DOUBLE NOT NULL DEFAULT 0, po3 DOUBLE NOT NULL DEFAULT 0, po4 DOUBLE NOT NULL DEFAULT 0, po5 DOUBLE NOT NULL DEFAULT 0, po6 DOUBLE NOT NULL DEFAULT 0, po7 DOUBLE NOT NULL DEFAULT 0, po8 DOUBLE NOT NULL DEFAULT 0, po9 DOUBLE NOT NULL DEFAULT 0, po10 DOUBLE NOT NULL DEFAULT 0, po11 DOUBLE NOT NULL DEFAULT 0, pso1 DOUBLE NOT NULL DEFAULT 0, pso2 DOUBLE NOT NULL DEFAULT 0,
  created_by INT UNSIGNED NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);
CREATE TABLE IF NOT EXISTS expert_lecture (
  sr INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, acad_year VARCHAR(20) NOT NULL, date DATE NOT NULL, sem VARCHAR(20) NOT NULL, title VARCHAR(255) NOT NULL, expert_name VARCHAR(255) NOT NULL,
  po1 DOUBLE NOT NULL DEFAULT 0, po2 DOUBLE NOT NULL DEFAULT 0, po3 DOUBLE NOT NULL DEFAULT 0, po4 DOUBLE NOT NULL DEFAULT 0, po5 DOUBLE NOT NULL DEFAULT 0, po6 DOUBLE NOT NULL DEFAULT 0, po7 DOUBLE NOT NULL DEFAULT 0, po8 DOUBLE NOT NULL DEFAULT 0, po9 DOUBLE NOT NULL DEFAULT 0, po10 DOUBLE NOT NULL DEFAULT 0, po11 DOUBLE NOT NULL DEFAULT 0, pso1 DOUBLE NOT NULL DEFAULT 0, pso2 DOUBLE NOT NULL DEFAULT 0,
  created_by INT UNSIGNED NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);
CREATE TABLE IF NOT EXISTS industry_visit (
  sr INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, acad_year VARCHAR(20) NOT NULL, date DATE NOT NULL, sem VARCHAR(20) NOT NULL, title VARCHAR(255) NOT NULL, place VARCHAR(255) NOT NULL,
  po1 DOUBLE NOT NULL DEFAULT 0, po2 DOUBLE NOT NULL DEFAULT 0, po3 DOUBLE NOT NULL DEFAULT 0, po4 DOUBLE NOT NULL DEFAULT 0, po5 DOUBLE NOT NULL DEFAULT 0, po6 DOUBLE NOT NULL DEFAULT 0, po7 DOUBLE NOT NULL DEFAULT 0, po8 DOUBLE NOT NULL DEFAULT 0, po9 DOUBLE NOT NULL DEFAULT 0, po10 DOUBLE NOT NULL DEFAULT 0, po11 DOUBLE NOT NULL DEFAULT 0, pso1 DOUBLE NOT NULL DEFAULT 0, pso2 DOUBLE NOT NULL DEFAULT 0,
  created_by INT UNSIGNED NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);
CREATE TABLE IF NOT EXISTS alumni_survey (
  sr INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, acad_year VARCHAR(20) NOT NULL, date DATE NOT NULL, title VARCHAR(255) NOT NULL,
  po1 DOUBLE NOT NULL DEFAULT 0, po2 DOUBLE NOT NULL DEFAULT 0, po3 DOUBLE NOT NULL DEFAULT 0, po4 DOUBLE NOT NULL DEFAULT 0, po5 DOUBLE NOT NULL DEFAULT 0, po6 DOUBLE NOT NULL DEFAULT 0, po7 DOUBLE NOT NULL DEFAULT 0, po8 DOUBLE NOT NULL DEFAULT 0, po9 DOUBLE NOT NULL DEFAULT 0, po10 DOUBLE NOT NULL DEFAULT 0, po11 DOUBLE NOT NULL DEFAULT 0, pso1 DOUBLE NOT NULL DEFAULT 0, pso2 DOUBLE NOT NULL DEFAULT 0,
  created_by INT UNSIGNED NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);
CREATE TABLE IF NOT EXISTS industry_survey (
  sr INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, acad_year VARCHAR(20) NOT NULL, date DATE NOT NULL, industry_details VARCHAR(500) NOT NULL,
  po1 DOUBLE NOT NULL DEFAULT 0, po2 DOUBLE NOT NULL DEFAULT 0, po3 DOUBLE NOT NULL DEFAULT 0, po4 DOUBLE NOT NULL DEFAULT 0, po5 DOUBLE NOT NULL DEFAULT 0, po6 DOUBLE NOT NULL DEFAULT 0, po7 DOUBLE NOT NULL DEFAULT 0, po8 DOUBLE NOT NULL DEFAULT 0, po9 DOUBLE NOT NULL DEFAULT 0, po10 DOUBLE NOT NULL DEFAULT 0, po11 DOUBLE NOT NULL DEFAULT 0, pso1 DOUBLE NOT NULL DEFAULT 0, pso2 DOUBLE NOT NULL DEFAULT 0,
  created_by INT UNSIGNED NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);

-- Course Exit Survey: CO values are nullable because a course may define fewer than six COs.
CREATE TABLE IF NOT EXISTS course_exit_survey (
  sr INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  acad_year VARCHAR(20) NOT NULL,
  sem VARCHAR(20) NOT NULL,
  c_name VARCHAR(255) NOT NULL,
  c_code VARCHAR(50) NOT NULL,
  c_coordinator VARCHAR(255) NOT NULL,
  co1 DOUBLE NULL DEFAULT NULL,
  co2 DOUBLE NULL DEFAULT NULL,
  co3 DOUBLE NULL DEFAULT NULL,
  co4 DOUBLE NULL DEFAULT NULL,
  co5 DOUBLE NULL DEFAULT NULL,
  co6 DOUBLE NULL DEFAULT NULL,
  created_by INT UNSIGNED NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_course_exit_year_sem (acad_year, sem),
  INDEX idx_course_exit_code (c_code),
  CONSTRAINT fk_course_exit_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);
